name: TinyPublisher CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./TinyPublisher
jobs:
  test-tiny:
    name: Test With Tiny
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Select Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Test With Tiny
        run: swift test --configuration debug --filter TinyPublisher
        working-directory: ./TinyPublisher
  test-combine:
    name: Test With Combine
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Select Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Test With Combine
        run: swift test --configuration debug --filter SwiftCombine 
        working-directory: ./TinyPublisher

 
